import { TMenuItemDrink, TMenuItemFood } from "../../interfaces/menuItem";

export const drinks: Array<TMenuItemDrink> = [
	{
		id: 1,
		name: "Mojito",
		description: "Refreshing mint cocktail with rum",
		price: 6.99,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 2,
		name: "Lemonade",
		description: "Freshly squeezed lemonade",
		price: 3.5,
		imageUrl: null,
		available: true,
		label: null,
		availableSizes: ["small", "medium", "large"],
	},
	{
		id: 3,
		name: "Craft Beer",
		description: "Locally brewed craft beer",
		price: 5.0,
		imageUrl: null,
		available: false,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 4,
		name: "Iced Tea",
		description: "Chilled tea with a hint of lemon",
		price: 2.99,
		imageUrl: null,
		available: true,
		label: null,
		availableSizes: ["medium", "large"],
	},
	{
		id: 5,
		name: "Whiskey Sour",
		description: "Whiskey mixed with lemon juice",
		price: 7.5,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 6,
		name: "Mineral Water",
		description: "Natural mineral water",
		price: 1.99,
		imageUrl: null,
		available: true,
		label: null,
		availableSizes: ["small", "standard", "large"],
	},
	{
		id: 7,
		name: "Gin and Tonic",
		description: "Gin mixed with tonic water",
		price: 6.5,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 8,
		name: "Orange Juice",
		description: "Freshly squeezed orange juice",
		price: 3.0,
		imageUrl: null,
		available: false,
		label: null,
		availableSizes: ["small", "medium"],
	},
	{
		id: 9,
		name: "Margarita",
		description: "Classic tequila-based cocktail",
		price: 7.0,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 10,
		name: "Coffee",
		description: "Freshly brewed coffee",
		price: 2.5,
		imageUrl: null,
		available: true,
		label: null,
		availableSizes: ["small", "medium", "large"],
	},
	{
		id: 11,
		name: "Vodka Martini",
		description: "Vodka with dry vermouth",
		price: 8.0,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 12,
		name: "Milkshake",
		description: "Creamy milkshake in various flavors",
		price: 4.0,
		imageUrl: null,
		available: false,
		label: null,
		availableSizes: ["medium", "large"],
	},
	{
		id: 13,
		name: "Pina Colada",
		description: "Tropical cocktail with rum, coconut, and pineapple",
		price: 6.5,
		imageUrl: null,
		available: true,
		label: "alcoholic",
		availableSizes: ["standard"],
	},
	{
		id: 14,
		name: "Apple Juice",
		description: "100% pure apple juice",
		price: 2.99,
		imageUrl: null,
		available: true,
		label: null,
		availableSizes: ["small", "medium"],
	},
];

export const food: Array<TMenuItemFood> = [
	{
		id: 1,
		name: "Cheeseburger",
		description:
			"A juicy cheeseburger with a beef patty, cheese, lettuce, and tomato",
		price: 8.99,
		imageUrl: null,
		available: true,
		label: null,
	},
	{
		id: 2,
		name: "Veggie Pizza",
		description: "Delicious pizza topped with a variety of vegetables",
		price: 10.5,
		imageUrl: null,
		available: true,
		label: "veggie",
	},
	{
		id: 3,
		name: "Chicken Wings",
		description:
			"Spicy and savory chicken wings served with a side of sauce",
		price: 7.99,
		imageUrl: null,
		available: false,
		label: null,
	},
	{
		id: 4,
		name: "Garden Salad",
		description:
			"Fresh garden salad with a mix of greens, tomatoes, and cucumbers",
		price: 6.99,
		imageUrl: null,
		available: true,
		label: "vegan",
	},
	{
		id: 5,
		name: "Steak",
		description:
			"Grilled steak cooked to your liking, served with vegetables",
		price: 15.99,
		imageUrl: null,
		available: true,
		label: null,
	},
	{
		id: 6,
		name: "Grilled Cheese Sandwich",
		description:
			"Classic grilled cheese sandwich with melted cheese on toasted bread",
		price: 5.99,
		imageUrl: null,
		available: true,
		label: "veggie",
	},
	{
		id: 7,
		name: "Spaghetti Carbonara",
		description:
			"Creamy spaghetti carbonara with bacon and parmesan cheese",
		price: 11.5,
		imageUrl: null,
		available: false,
		label: null,
	},
	{
		id: 8,
		name: "Fish and Chips",
		description:
			"Crispy fish and chips served with tartar sauce and lemon wedges",
		price: 9.5,
		imageUrl: null,
		available: true,
		label: null,
	},
];
