const menu = {
	food: [
		{
			id: 1,
			name: "Cheeseburger",
			price: 8.99,
			vegetarian: false,
			rating: 4.5,
			available: true,
		},
		{
			id: 2,
			name: "Veggie Pizza",
			price: 10.5,
			vegetarian: true,
			rating: 4.7,
			available: true,
		},
		{
			id: 3,
			name: "Chicken Wings",
			price: 7.99,
			vegetarian: false,
			rating: 4.3,
			available: false,
		},
		{
			id: 4,
			name: "Garden Salad",
			price: 6.99,
			vegetarian: true,
			rating: 4.6,
			available: true,
		},
		{
			id: 5,
			name: "Steak",
			price: 15.99,
			vegetarian: false,
			rating: 4.8,
			available: true,
		},
		{
			id: 6,
			name: "Grilled Cheese Sandwich",
			price: 5.99,
			vegetarian: true,
			rating: 4.2,
			available: true,
		},
		{
			id: 7,
			name: "Spaghetti Carbonara",
			price: 11.5,
			vegetarian: false,
			rating: 4.5,
			available: false,
		},
		{
			id: 8,
			name: "Fish and Chips",
			price: 9.5,
			vegetarian: false,
			rating: 4.4,
			available: true,
		},
	],
	drinks: [
		{
			id: 1,
			name: "Mojito",
			price: 6.99,
			alcoholic: true,
			rating: 4.5,
			available: true,
		},
		{
			id: 2,
			name: "Lemonade",
			price: 3.5,
			alcoholic: false,
			rating: 4.6,
			available: true,
		},
		{
			id: 3,
			name: "Craft Beer",
			price: 5.0,
			alcoholic: true,
			rating: 4.7,
			available: false,
		},
		{
			id: 4,
			name: "Iced Tea",
			price: 2.99,
			alcoholic: false,
			rating: 4.3,
			available: true,
		},
		{
			id: 5,
			name: "Whiskey Sour",
			price: 7.5,
			alcoholic: true,
			rating: 4.8,
			available: true,
		},
		{
			id: 6,
			name: "Mineral Water",
			price: 1.99,
			alcoholic: false,
			rating: 4.9,
			available: true,
		},
		{
			id: 7,
			name: "Gin and Tonic",
			price: 6.5,
			alcoholic: true,
			rating: 4.4,
			available: true,
		},
		{
			id: 8,
			name: "Orange Juice",
			price: 3.0,
			alcoholic: false,
			rating: 4.2,
			available: false,
		},
		{
			id: 9,
			name: "Margarita",
			price: 7.0,
			alcoholic: true,
			rating: 4.6,
			available: true,
		},
		{
			id: 10,
			name: "Coffee",
			price: 2.5,
			alcoholic: false,
			rating: 4.7,
			available: true,
		},
		{
			id: 11,
			name: "Vodka Martini",
			price: 8.0,
			alcoholic: true,
			rating: 4.5,
			available: true,
		},
		{
			id: 12,
			name: "Milkshake",
			price: 4.0,
			alcoholic: false,
			rating: 4.6,
			available: false,
		},
		{
			id: 13,
			name: "Pina Colada",
			price: 6.5,
			alcoholic: true,
			rating: 4.3,
			available: true,
		},
		{
			id: 14,
			name: "Apple Juice",
			price: 2.99,
			alcoholic: false,
			rating: 4.4,
			available: true,
		},
		{
			id: 15,
			name: "Tequila Sunrise",
			price: 7.0,
			alcoholic: true,
			rating: 4.2,
			available: true,
		},
		{
			id: 16,
			name: "Soda",
			price: 1.99,
			alcoholic: false,
			rating: 4.5,
			available: true,
		},
	],
};

export default menu;
